name: Build Windows .exe using pyinstaller

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Merge requirements
      run: cat src/requirements.txt >> build/requirements.txt

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: build
        requirements: requirements.txt

    - uses: actions/upload-artifact@v4
      with:
        name: chirplab-win
        path: build/dist/windows


  release:
      name: Add bundled executable to release
      needs: build
      runs-on: ubuntu-latest
      if: startsWith(github.ref, 'refs/tags/')
      
      steps:
      - run: cd build/dist/windows; zip -r chirplab_${{  github.ref_name }}_win.zip *; cd ../../../
      - uses: softprops/action-gh-release@v2
        with:
          files: build/dist/windows/chirplab_${{  github.ref_name }}_win.zip



